version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-creds/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-creds/password
    DOCKER_REGISTRY_URL: /myapp/docker-creds/docker_registry_url
  variables:
    IMAGE_REPO_NAME: simple-python-flask-app
    IMAGE_TAG: latest

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r day-14/simple-python-app/requirements.txt
  build:
    commands:
      - echo "Running tests..."
      - cd day-14/simple-python-app/
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t $DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/$IMAGE_REPO_NAME:$IMAGE_TAG .
      
  post_build:
    commands:
      - echo "Build completed successfully!"
      - echo "Pushing the Docker images..."
      - docker push $DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/$IMAGE_REPO_NAME:$IMAGE_TAG
